
INSERT INTO `sales` (`value`) VALUES
('0'),('5'),('10'),('15'),('20'),('25'),('30'),('40'),('45'),('50'),('55'),('60'),('65'),('70'),('75'),('80'),('85'),('90'),('95'),('100');

INSERT INTO `categories` ( `name`, `description`, `image`) VALUES
( 'Bánh mặn', 'Nếu từng bị mê hoặc bởi các loại tarlet ngọt thì chắn chắn bạn không thể bỏ qua những loại tarlet mặn. Ngoài hình dáng bắt mắt, lớp vở bánh giòn giòn cùng với nhân mặn như thịt gà, nấm, thị heo ,… của bánh sẽ chinh phục bất cứ ai dùng thử.', 'banh-man-thu-vi-nhat-1.jpg'),
( 'Bánh ngọt', 'Bánh ngọt là một loại thức ăn thường dưới hình thức món bánh dạng bánh mì từ bột nhào, được nướng lên dùng để tráng miệng. Bánh ngọt có nhiều loại, có thể phân loại dựa theo nguyên liệu và kỹ thuật chế biến như bánh ngọt làm từ lúa mì, bơ, bánh ngọt dạng bọt biển. Bánh ngọt có thể phục vụ những mục đính đặc biệt như bánh cưới, bánh sinh nhật, bánh Giáng sinh, bánh Halloween..', '20131108144733.jpg'),
( 'Bánh trái cây', 'Bánh trái cây, hay còn gọi là bánh hoa quả, là một món ăn chơi, không riêng gì của Huế nhưng khi \"lạc\" vào mảnh đất Cố đô, món bánh này dường như cũng mang chút tinh tế, cầu kỳ và đặc biệt. Lấy cảm hứng từ những loại trái cây trong vườn, qua bàn tay khéo léo của người phụ nữ Huế, món bánh trái cây ra đời - ngọt thơm, dịu nhẹ làm đẹp lòng biết bao người thưởng thức.', 'banhtraicay.jpg'),
( 'Bánh kem', 'Với người Việt Nam thì bánh ngọt nói chung đều hay được quy về bánh bông lan – một loại tráng miệng bông xốp, ăn không hoặc được phủ kem lên thành bánh kem. Tuy nhiên, cốt bánh kem thực ra có rất nhiều loại với hương vị, kết cấu và phương thức làm khác nhau chứ không chỉ đơn giản là “bánh bông lan” chung chung đâu nhé!', 'banhkem.jpg'),
( 'Bánh crepe', 'Crepe là một món bánh nổi tiếng của Pháp, nhưng từ khi du nhập vào Việt Nam món bánh đẹp mắt, ngon miệng này đã làm cho biết bao bạn trẻ phải “xiêu lòng”', 'crepe.jpg'),
( 'Bánh Pizza', 'Pizza đã không chỉ còn là một món ăn được ưa chuộng khắp thế giới mà còn được những nhà cầm quyền EU chứng nhận là một phần di sản văn hóa ẩm thực châu Âu. Và để được chứng nhận là một nhà sản xuất pizza không hề đơn giản. Người ta phải qua đủ mọi các bước xét duyệt của chính phủ Ý và liên minh châu Âu nữa… tất cả là để đảm bảo danh tiếng cho món ăn này.', 'pizza.jpg' ),
( 'Bánh su kem', 'Bánh su kem là món bánh ngọt ở dạng kem được làm từ các nguyên liệu như bột mì, trứng, sữa, bơ.... đánh đều tạo thành một hỗn hợp và sau đó bằng thao tác ép và phun qua một cái túi để định hình thành những bánh nhỏ và cuối cùng được nướng chín. Bánh su kem có thể thêm thành phần Sô cô la để tăng vị hấp dẫn. Bánh có xuất xứ từ nước Pháp.', 'sukemdau.jpg');


INSERT INTO `products` ( `name`, `category_id`, `description`,`price`,  `image`, `amount`,`type`,`sales_id`) VALUES
 ( 'Bánh Crepe Sầu riêng', 5, 'Bánh crepe sầu riêng nhà làm', 150000, '1430967449-pancake-sau-rieng-6.jpg', 16,'hộp',1),
 ( 'Bánh Crepe Chocolate', 5, 'Bánh crepe sầu riêng nhà làm', 180000,  'crepe-chocolate.jpg', 15,'hộp',2),
 ( 'Bánh Crepe Sầu riêng - Chuối', 5, 'Bánh crepe sầu riêng nhà làm', 150000, 'crepe-chuoi.jpg',30,'hộp',3),
 ( 'Bánh Crepe Đào', 5, 'Bánh crepe sầu riêng nhà làm', 160000, 'crepe-dao.jpg',40,'hộp',4),
 ( 'Bánh Crepe Dâu', 5, 'Bánh crepe sầu riêng nhà làm', 160000, 'crepedau.jpg', 55,'hộp',5),
 ( 'Bánh Crepe Pháp', 5, 'Bánh crepe sầu riêng nhà làm', 200000, 'crepe-phap.jpg',41,'hộp',6),
 ( 'Bánh Crepe Táo', 5, 'Bánh crepe sầu riêng nhà làm', 160000,  'crepe-tao.jpg',60,'hộp',7),
 ( 'Bánh Crepe Trà xanh', 5, 'Bánh crepe sầu riêng nhà làm', 160000,  'crepe-traxanh.jpg',60,'hộp',8),
 ( 'Bánh Crepe Sầu riêng và Dứa', 5, 'Bánh crepe sầu riêng nhà làm', 160000,  'saurieng-dua.jpg',12,'hộp',9),
 ( 'Bánh Gato Trái cây Việt Quất', 3, 'Bánh crepe sầu riêng nhà làm', 250000, '544bc48782741.png',65,'hộp',1),
 ( 'Bánh sinh nhật rau câu trái cây', 3, 'Bánh crepe sầu riêng nhà làm', 200000, '210215-banh-sinh-nhat-rau-cau-body- (6).jpg', 12,'hộp',2),
 ( 'Bánh kem Chocolate Dâu', 3, 'Bánh crepe sầu riêng nhà làm', 300000,  'banh kem sinh nhat.jpg', 45,'hộp',3),
 ( 'Bánh kem Dâu III', 3, 'Bánh crepe sầu riêng nhà làm', 300000, 'Banh-kem (6).jpg', 45,'hộp',4),
 ( 'Bánh kem Dâu I', 3, 'Bánh crepe sầu riêng nhà làm', 350000,'banhkem-dau.jpg', 50, 'cái',5),
 ( 'Bánh trái cây II', 3, 'Bánh crepe sầu riêng nhà làm', 150000,  'banhtraicay.jpg', 50, 'hộp',6),
 ( 'Apple Cake', 3, 'Bánh crepe sầu riêng nhà làm', 250000, 'Fruit-Cake_7979.jpg', 54, 'cái',7),
 ( 'Bánh ngọt nhân cream táo', 2, 'Bánh crepe sầu riêng nhà làm', 180000, '20131108144733.jpg', 44, 'hộp',8),
 ( 'Bánh Chocolate Trái cây', 2, 'Bánh crepe sầu riêng nhà làm', 150000, 'Fruit-Cake_7976.jpg', 12, 'hộp',9),
( 'Bánh Chocolate Trái cây II', 2, 'Bánh crepe sầu riêng nhà làm', 150000,'Fruit-Cake_7981.jpg', 45, 'hộp',10),
( 'Peach Cake', 2, 'Bánh crepe sầu riêng nhà làm', 160000,  'Peach-Cake_3294.jpg', 78, 'cái',11),
( 'Bánh bông lan trứng muối I', 1, 'Bánh crepe sầu riêng nhà làm', 160000,  'banhbonglantrung.jpg', 45, 'hộp',1),
( 'Bánh bông lan trứng muối II', 1, 'Bánh crepe sầu riêng nhà làm', 180000,  'banhbonglantrungmuoi.jpg', 45, 'hộp',2),
( 'Bánh French', 1, 'Bánh nhà làm', 180000, 'banh-man-thu-vi-nhat-1.jpg', 56, 'hộp',3),
('Bánh mì Australia', 1, 'Bánh nhà làm', 80000, 'dung-khoai-tay-lam-banh-gato-man-cuc-ngon.jpg', 78, 'hộp',3),
( 'Bánh mặn thập cẩm', 1, 'Bánh nhà làm', 50000, 'Fruit-Cake.png', 54, 'hộp',4),
( 'Bánh Muffins trứng', 1, 'Bánh nhà làm', 100000,  'maxresdefault.jpg', 78, 'hộp',5),
( 'Bánh Scone Peach Cake', 1, 'Bánh nhà làm', 120000,  'Peach-Cake_3300.jpg', 78, 'hộp',6),
( 'Bánh mì Loaf I', 1, 'Bánh nhà làm', 100000, 'sli12.jpg', 45, 'hộp',6),
( 'Bánh kem Chocolate Dâu I', 4, 'Bánh nhà làm', 380000,  'sli12.jpg', 44, 'cái',7),
( 'Bánh kem Trái cây I', 4, 'Bánh nhà làm', 380000,  'Fruit-Cake.jpg', 4, 'cái',9),
( 'Bánh kem Trái cây II', 4, 'Bánh nhà làm', 380000, 'Fruit-Cake_7971.jpg', 45, 'cái',10),
( 'Bánh kem Doraemon', 4, 'Bánh nhà làm', 280000,  'p1392962167_banh74.jpg', 46, 'cái',4),
( 'Bánh kem Caramen Pudding', 4, 'Bánh nhà làm', 280000,  'Caramen-pudding636099031482099583.jpg', 42, 'cái',1),
( 'Bánh kem Chocolate Fruit', 4, 'Bánh nhà làm', 320000,  'chocolate-fruit636098975917921990.jpg', 13, 'cái',5),
( 'Bánh kem Coffee Chocolate GH6', 4, 'Bánh nhà làm', 320000, 'COFFE-CHOCOLATE636098977566220885.jpg', 5, 'cái',13),
('Bánh kem Mango Mouse', 4, 'Bánh nhà làm', 320000, 'mango-mousse-cake.jpg', 4, 'cái',4),
( 'Bánh kem Matcha Mouse', 4, 'Bánh nhà làm', 350000,  'MATCHA-MOUSSE.jpg', 12, 'cái',5),
( 'Bánh kem Flower Fruit', 4, 'Bánh nhà làm', 350000, 'flower-fruits636102461981788938.jpg', 45, 'cái',6),
( 'Bánh kem Strawberry Delight', 4, 'Bánh nhà làm', 350000, 'strawberry-delight636102445035635173.jpg', 4, 'cái',9),
( 'Bánh kem Raspberry Delight', 4, 'Bánh nhà làm', 350000,  'raspberry.jpg', 5, 'cái',12),
( 'Beefy Pizza', 6, 'Thịt bò xay, ngô, sốt BBQ, phô mai mozzarella', 150000,  '40819_food_pizza.jpg', 45, 'cái',9),
( 'Hawaii Pizza', 6, 'Sốt cà chua, ham , dứa, pho mai mozzarella', 120000, 'hawaiian paradise_large-900x900.jpg', 65, 'cái',6),
( 'Smoke Chicken Pizza', 6, 'Gà hun khói,nấm, sốt cà chua, pho mai mozzarella.', 120000,  'chicken black pepper_large-900x900.jpg', 34, 'cái',8),
( 'Sausage Pizza', 6, 'Xúc xích klobasa, Nấm, Ngô, sốtcà chua, pho mai Mozzarella.', 120000, 'pizza-miami.jpg', 54, 'cái',5),
( 'Ocean Pizza', 6, 'Tôm , mực, xào cay,ớt xanh, hành tây, cà chua, phomai mozzarella.', 120000,  'seafood curry_large-900x900.jpg', 32, 'cái',6),
( 'All Meaty Pizza', 6, 'Ham, bacon, chorizo, pho mai mozzarella.', 140000, 'all1).jpg', 54, 'cái',3),
( 'Tuna Pizza', 6, 'Cá Ngừ, sốt Mayonnaise,sốt càchua, hành tây, pho mai Mozzarella', 140000, '54eaf93713081_-_07-germany-tuna.jpg', 76, 'cái',9),
( 'Bánh su kem nhân dừa', 7, 'Bánh nhà làm', 120000, 'maxresdefault.jpg', 45, 'cái',5),
( 'Bánh su kem sữa tươi', 7, 'Bánh nhà làm', 120000,'sukem.jpg', 31, 'cái',4),
( 'Bánh su kem sữa tươi chiên giòn', 7, 'Bánh nhà làm', 150000, '1434429117-banh-su-kem-chien-20.jpg', 31, 'hộp',6),
( 'Bánh su kem dâu sữa tươi', 7, 'Bánh nhà làm', 150000, 'sukemdau.jpg', 65, 'hộp',8),
( 'Bánh su kem bơ sữa tươi', 7, 'Bánh nhà làm', 150000, 'He-Thong-Banh-Su-Singapore-Chewy-Junior.jpg', 54, 'hộp',11),
( 'Bánh su kem nhân trái cây sữa tươi', 7, 'Bánh nhà làm', 150000, 'foody-banh-su-que-635930347896369908.jpg', 75, 'hộp',12),
( 'Bánh su kem cà phê', 7, 'Bánh nhà làm', 150000,'banh-su-kem-ca-phe-1.jpg', 45, 'hộp',13),
( 'Bánh su kem phô mai', 7, 'Bánh nhà làm', 150000,  '50020041-combo-20-banh-su-que-pho-mai-9.jpg', 54, 'hộp',8),
( 'Bánh su kem sữa tươi chocolate', 7, 'Bánh nhà làm', 150000, 'combo-20-banh-su-que-kem-sua-tuoi-phu-socola.jpg', 45, 'hộp',6),
( 'Bánh Macaron Pháp', 2, 'Thưởng thức macaron, người ta có thể tìm thấy từ những hương vị truyền thống như mâm xôi, chocolate, cho đến những hương vị mới như nấm và trà xanh. Macaron với vị giòn tan của vỏ bánh, béo ngậy ngọt ngào của phần nhân, với vẻ ngoài đáng yêu và nhiều màu sắc đẹp mắt, đây là món bạn không nên bỏ qua khi khám phá nền ẩm thực Pháp.', 200000, 'Macaron9.jpg', 45,'cái',12),
('Bánh Tiramisu - Italia', 2, 'Chỉ cần cắn một miếng, bạn sẽ cảm nhận được tất cả các hương vị đó hòa quyện cùng một chính vì thế người ta còn ví món bánh này là Thiên đường trong miệng của bạn', 200000, '234.jpg',45,'cái',10),
( 'Bánh Táo - Mỹ', 2, 'Bánh táo Mỹ với phần vỏ bánh mỏng, giòn mềm, ẩn chứa phần nhân táo thơm ngọt, điểm chút vị chua dịu của trái cây quả sẽ là một lựa chọn hoàn hảo cho những tín đồ bánh ngọt trên toàn thế giới.', 200000, '1234.jpg', 75,'cái',13),
( 'Bánh Cupcake - Anh Quốc', 6, 'Những chiếc cupcake có cấu tạo gồm phần vỏ bánh xốp mịn và phần kem trang trí bên trên rất bắt mắt với nhiều hình dạng và màu sắc khác nhau. Cupcake còn được cho là chiếc bánh mang lại niềm vui và tiếng cười như chính hình dáng đáng yêu của chúng.', 150000,  'cupcake.jpg', 45, 'cái',13),
( 'Bánh Sachertorte', 6, 'Sachertorte là một loại bánh xốp được tạo ra bởi loại&nbsp;chocholate&nbsp;tuyệt hảo nhất của nước Áo. Sachertorte có vị ngọt nhẹ, gồm nhiều lớp bánh được làm từ ruột bánh mì và bánh sữa chocholate, xen lẫn giữa các lớp bánh là mứt mơ. Món bánh chocholate này nổi tiếng tới mức thành phố Vienna của Áo đã ấn định&nbsp;tổ chức một ngày Sachertorte quốc gia, vào 5/12 hằng năm', 250000, '111.jpg', 45, 'cái',11);
